### ISSUE TITLE
Prepare JOSS submission 

### ISSUE THREAD

**Issue by InterdisciplinaryPhysicsTeam** [JuliaGraphs/MultilayerGraphs.jl#42]
- [X] Open an [issue](https://github.com/openjournals/joss/issues/1168) with pre-submission enquiry
- [X] Create a new [branch](https://github.com/JuliaGraphs/MultilayerGraphs.jl/tree/JOSS) for the JOSS submission 
- [X] Add [GitHub action](https://github.com/JuliaGraphs/MultilayerGraphs.jl/blob/JOSS/.github/workflows/PaperDraft.yml) for the JOSS paper draft which will be uploaded [here](https://github.com/JuliaGraphs/MultilayerGraphs.jl/blob/JOSS/paper/paper.pdf)
- [X] Include a list of the *authors* of the software and their affiliations
- [x] Include a *summary* describing the high-level functionality and purpose of the software for a diverse, non-specialist audience
- [x] Include a *statement of need* section that clearly illustrates the research purpose of the software and places it in the context of related work
- [x] Include a *main features* section illustrating the main functionalities of the package
- [x] Include a *installation and usage* section showcasing the main functionalities of the package
- [x] Include a list of *key references*, including to other software addressing related needs. Note that the references should include full names of venues, e.g., journals and conferences, not abbreviations only understood in the context of a specific discipline
- [x] Mention (if applicable) a representative set of past or ongoing research projects using the software and recent scholarly publications enabled by it
- [x] Acknowledgement of any financial support

**NB:** A “full length” paper is not permitted, and software documentation such as API (Application Programming Interface) functionality should not be in the paper and instead should be outlined in the software documentation.

**Comment by InterdisciplinaryPhysicsTeam** [comment]
# Paper Structure 

## Summary 
- [ ] One or two sentences on the mathematical formulation of graphs (with $\LaTeX$ code) and scientific applications citing the relevant scientific literature
- [ ] One or two sentences on the mathematical formulation of multilayer graphs (with $\LaTeX$ code) and scientific applications citing the relevant scientific literature
- [ ] 

## Statement of Need
- [ ] General: 
- [ ] Particular: there were no software packages for the creation, manipulation and analysis of multilayer graphs written in Julia

## Main Features 
- [ ] Main structs 
- [ ] Main methods 
- [ ] Extension of Graphs.jl ecosystem 
- [ ] Integration with Agents.jl ecosystem 

## References

**Comment by pitmonticone** [comment]
## Must Read

- [ ] https://joss.theoj.org/papers/search?page=5&q=graphs
- [ ] https://joss.theoj.org/papers/10.21105/joss.04561
- [ ] https://joss.theoj.org/papers/10.21105/joss.04869
- [ ] https://joss.theoj.org/papers/10.21105/joss.04312
- [ ] https://joss.theoj.org/papers/10.21105/joss.04694
- [ ] https://joss.theoj.org/papers/10.21105/joss.04157
- [ ] https://joss.theoj.org/papers/10.21105/joss.04575
- [ ] https://joss.theoj.org/papers/10.21105/joss.04452
- [ ] https://joss.theoj.org/papers/10.21105/joss.04442
- [ ] https://joss.theoj.org/papers/10.21105/joss.04414
- [ ] https://joss.theoj.org/papers/10.21105/joss.04556
- [ ] https://joss.theoj.org/papers/10.21105/joss.03527
- [ ] https://joss.theoj.org/papers/10.21105/joss.03974
- [ ] https://joss.theoj.org/papers/10.21105/joss.04565
- [ ] https://joss.theoj.org/papers/10.21105/joss.04736
- [ ] https://joss.theoj.org/papers/10.21105/joss.04775
- [ ] https://joss.theoj.org/papers/10.21105/joss.04129

**Comment by pitmonticone** [comment]
## Must Cite 

### Julia Language and Packages 
- [ ] JuliaLang: https://doi.org/10.1137/141000671
- [ ] Agents.jl: https://doi.org/10.1177/00375497211068820

**Comment by pitmonticone** [comment]
# Related Packages 
## R 
- [ ] https://github.com/manlius/muxViz
- [ ] https://github.com/marmello77/multilayer-networks

## Python
- [ ] 

## Julia 
- [ ]

**Comment by pitmonticone** [comment]
We have submitted the MultilayerGraphs.jl paper to JOSS. 

[Here](https://github.com/openjournals/joss-reviews/issues/5055) you can follow the open review process.
